   name: C/C++ CI

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: build application
        run: make
